language: haskell

install:
    - ghc --version
    - cabal --version
    - sudo apt-get install libfcgi-dev
    - cabal unpack wai-logger
    - mv wai-logger-* wai-logger
    - cabal install hspec doctest HTTP cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script: mega-sdist --test
